name: Call Semgrep composite action

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  code-scan:
    name: Call composite action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: relsqui/docker-semgrep-test@2
        with:
          semgrep-app-token: ${{ secrets.SEMGREP_APP_TOKEN }}
