---
name: "Test workflow dispatch boolean input"

on:
  workflow_dispatch:
    inputs:
      box_ticked:
        description: "Did you tick the box?"
        type: boolean

env:
  BOX_TICKED: ${{ inputs.box_ticked && 'yes' || 'no' }}

jobs:
  check-box:
    runs-on: ubuntu-latest
    steps:
      - run: echo "was the box ticked? ${BOX_TICKED}!"
