---
name: "Generate Links"

on:
  workflow_dispatch

jobs:
  make-links:
    runs-on: ubuntu-20.04
    steps:
      - name: Print some IDs
        run: |
          echo "Run summary: https://github.com/relsqui/workflow-testing/actions/runs/${{ github.run_id }}"
          echo "??: https://github.com/relsqui/workflow-testing/actions/runs/${GITHUB_RUN_ID}"
