---
name: "Test third-party membership checking action"
run-name: "Checking if ${{ github.actor }} is in ${{ inputs.team-slug }}"

on:
  workflow_dispatch:
    inputs:
      team-slug:
        description: team slug (get from url of membership page)

jobs:
  check-membership:
    runs-on: ubuntu-latest
    steps:
    - id: get-members
      uses: GuillaumeFalourd/github-team-members@main
      with:
        org_slug: OpenSesame
        team_slug: ${{ inputs.team-slug }}
        token: ${{ secrets.ORG_READ_TOKEN }}
    - run: echo '${{ toJson(steps.get-members.outputs) }}' | jq
