---
name: "Check group membership of workflow dispatcher"

on:
  workflow_dispatch:
    inputs:
      team-slug:
        description: team slug (get from url of membership page)

jobs:
  check-membership:
    runs-on: ubuntu-latest
    steps:
    - id: get-all-members
      run: |
        echo "checking if ${{ github.actor }} is in ${TEAM_SLUG}"
        gh api --paginate -X GET /orgs/OpenSesame/teams/$TEAM_SLUG/members | jq -e 'any(.login == "${{ github.actor }}")'
      env:
        TEAM_SLUG: ${{ inputs.team-slug }}
        GH_TOKEN: ${{ secrets.ORG_READ_TOKEN }}
