---
name: "Check group membership of workflow dispatcher"

on:
  workflow_dispatch:
    inputs:
      team-slug:
        description: team slug (get from url)

jobs:
  check-membership:
    runs-on: ubuntu-latest
    steps:
    - id: get-all-members
      run: |
        data=$(gh api --paginate -X GET /orgs/$ORG_SLUG/teams/$TEAM_SLUG/members\?role=$ROLE | jq 'reduce inputs as $i (.; . += $i)')
        echo "$data" | jq
      env:
        ORG_SLUG: OpenSesame
        TEAM_SLUG: ${{ inputs.team-slug }}
        GH_TOKEN: ${{ secrets.ORG_READ_TOKEN }}
