name: Read a boolean input in a scheduled job

on:
  schedule:
    # highest supported frequency is every five minutes
    - cron: '5,10,15,20,25,30,35,40,45,50,55 * * * *'
  workflow_dispatch:
    inputs:
      human:
        description: Did a human start this workflow?
        type: boolean
        default: true

jobs:
  report-boolean:
    name: Report boolean state
    runs-on: ubuntu-latest
    env:
      BOOLEAN_STATE: ${{ !!(inputs.human) }}
    steps:
      - name: Output boolean
        run: echo "'${BOOLEAN_STATE}'"
