---
name: "Upsert comment"

on:
  workflow_dispatch:
  push:

jobs:
  upsert-comment:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: first step
        id: first
        run: echo "::set-output name=keysmash::asldfkij"
      - name: second step
        id: second
        run: echo "::set-output name=keysmash::wfuensdk"
      - name: third step
        id: third
        run: echo "::set-output name=keysmash::cmhfekjh"
      - uses: jwalton/gh-find-current-pr@v1
        id: find_pr
      - name: "Check for existing comment"
        uses: peter-evans/find-comment@v1
        id: find_comment
        with:
          issue-number: ${{ steps.find_pr.outputs.pr }}
          comment-author: 'github-actions[bot]'
          body-includes: <!-- Automatic Comment -->
      - name: "Post or update comment"
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ steps.find_pr.outputs.pr }}
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            <!-- Automatic Comment -->
            <details>
              <summary>Click for info about this automatic comment.</summary>

              ```
              Pull Request: ${{ steps.find_pr.outputs.pr }}
              Comment ID: ${{ steps.find_comment.outputs.comment-id }}
              Steps: ${{ toJson(steps) }}
              ```
            </details>
