---
name: "Upsert comment"

on:
  workflow_dispatch:
  push:

jobs:
  make-matrix:
    runs-on: ubuntu-20.04
    outputs:
      matrix: "{'include':[{'animal':'bear','color':'black'},{'animal':'bear','color':'brown'},{'animal':'snake','color':'black'}]}"
    steps:
      - name: do nothing
        run: echo "jobs are required to do at least one thing"
  generate-output:
    runs-on: ubuntu-20.04
    needs: make-matrix
    strategy:
      matrix: ${{ fromJson(needs.make-matrix.outputs.matrix)}}
    outputs:
      all: ${{ toJson(steps) }}
    steps:
      - name: '${{ matrix.color }}-${{ matrix.animal }}'
        run: echo "::set-output name=exclamation::Look out, a ${{ matrix.color }} ${{ matrix.animal }}!"
  aggregate-output:
    runs-on: ubuntu-20.04
    needs: [make-matrix, generate-output]
    steps:
      - name: aggregate output
        run: |
          MATRIX="${{ needs.make-matrix.outputs.matrix }}"
          echo "$MATRIX" | jq
  upsert-comment:
    runs-on: ubuntu-20.04
    needs: generate-output
    steps:
      - uses: actions/checkout@v2
      - uses: jwalton/gh-find-current-pr@v1
        id: find_pr
      - name: "Check for existing comment"
        uses: peter-evans/find-comment@v1
        id: find_comment
        with:
          issue-number: ${{ steps.find_pr.outputs.pr }}
          comment-author: 'github-actions[bot]'
          body-includes: <!-- Automatic Comment -->
      - name: "Post or update comment"
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ steps.find_pr.outputs.pr }}
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            <!-- Automatic Comment -->
            <details open>
              <summary>Click for info about this automatic comment.</summary>

              ```
              Pull Request: ${{ steps.find_pr.outputs.pr }}
              Comment ID: ${{ steps.find_comment.outputs.comment-id }}
              Outputs: ${{ needs.generate-output.outputs.all }}
              ```
            </details>
