---
name: Get conclusion of a long workflow
run-name: "Get conclusion of ${{ inputs.job-count }} jobs (FF: ${{ inputs.fail-fast }})"

on:
  workflow_dispatch:
    inputs:
      job-count:
        type: number
        description: How many jobs to make?
      fail-fast:
        type: boolean
        default: true
        description: "Fail fast?"

jobs:
  make-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.make-matrix.outputs.matrix }}
    steps:
      - id: make-matrix
        run: |
          seq_max=$(( ${{ inputs.job-count }} - 1 ))
          matrix=$(echo -n '{"index": ['; for x in $(seq "$seq_max"); do echo -n $x,; done; echo '${{ inputs.job-count }}]}')
          echo "$matrix"
          echo "matrix=${matrix}" >> "$GITHUB_OUTPUT"
  lots-of-jobs:
    runs-on: ubuntu-latest
    needs: make-matrix
    strategy:
      matrix: ${{ fromJson(needs.make-matrix.outputs.matrix) }}
      fail-fast: ${{ inputs.fail-fast }}
    steps:
      - name: job ${{ matrix.index }}
        run: |
          [ "${{ matrix.index }}" != "${{ inputs.job-count }}" ]
  get-conclusion:
    runs-on: ubuntu-latest
    needs: lots-of-jobs
    if: always()
    steps:
      - id: get-conclusion
        uses: relsqui/workflow-conclusion-action@false-positive-testing
      - run: |
          cat <<EOF > all-jobs.json
            ${{ steps.get-conclusion.outputs.jobs }}
          EOF
      - uses: actions/upload-artifact@v3
        with:
          path: all-jobs.json
      - if: env.WORKFLOW_CONCLUSION != 'failure'
        run: exit 1
