---
name: Get conclusion of a long workflow

on:
  workflow_dispatch:
    inputs:
      job-count:
        type: number
        description: How many jobs to make?

jobs:
  make-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.make-matrix.outputs.matrix }}
    steps:
      - id: make-matrix
        run: |
          matrix=$(echo -n '{"index": ['; for x in $(seq ${{ inputs.job-count - 1 }}); do echo -n $x,; done; echo '${{ inputs.job-count }}]}')
          echo "matrix=${matrix}" >> "$GITHUB_OUTPUT"
  lots-of-jobs:
    runs-on: ubuntu-latest
    needs: make-matrix
    strategy:
      matrix: ${{ fromJson(needs.make-matrix.outputs.matrix) }}
      fail-fast: false
    steps:
      - run: |
          [ "${{ matrix.index }}" != "${{ inputs.job-count }}" ]
  get-conclusion:
    runs-on: ubuntu-latest
    needs: lots-of-jobs
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v3