---
name: Get conclusion of a long workflow

on:
  workflow_dispatch:

jobs:
  make-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.make-matrix.outputs.matrix }}
    steps:
      - id: make-matrix
        run: |
          matrix=$(echo -n '{"index": ['; for x in $(seq 199); do echo -n $x,; done; echo '200]}')
          echo "matrix=${matrix}" >> "$GITHUB_OUTPUT"
  lots-of-jobs:
    runs-on: ubuntu-latest
    needs: make-matrix
    strategy:
      matrix: ${{ fromJson(needs.make-matrix.outputs.matrix) }}
    steps:
      - run: |
          [ "${{ matrix.index }}" != "200" ]
  get-conclusion:
    runs-on: ubuntu-latest
    needs: lots-of-jobs
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v3